<?php

########################################################################
# Extension Manager/Repository config file for ext: "pf_featured_products"
#
# Auto generated by Extension Builder 2012-10-16
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Fluid Content: Grid elements',
	'description' => 'A collection of grid elements written for EXT:fluidcontent using ViewHelpers from EXT:vhs',
	'category' => 'misc',
	'author' => 'Andy Hausmann',
	'author_email' => 'ah@sota-studio.de',
	'author_company' => 'sota studio',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array (
		'depends' => array (
			'typo3' => '4.5-0.0.0',
			'cms' => '',
			'fluidcontent' => '',
			'vhs' => '',
		),
		'conflicts' => '',
		'suggests' => array (
		),
	),
);

?>(
		),
	),
);

?>